spring:
  application:
    name: latteve_spring
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver



  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect # MySQL 방언 설정
        show_sql: true
        format_sql: true
        use_sql_comments: true
        generate_statistics: true
        jdbc:
          batch_size: 20
        default_batch_fetch_size: 100


  config:
    import: "classpath:application-secret.yml, classpath:application-oauth.yml"

  profiles:
    active: secret, oauth

logging:
  level:
    org.hibernate.stat: debug
    org.hibernate.SQL: DEBUG # SQL 쿼리를 출력
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # SQL 쿼리의 파라미터 값을 출력
    org.springframework.amqp: DEBUG
    org.springframework.rabbit: DEBUG
    com.rabbitmq: DEBUG
    root: INFO
    site.hesil: DEBUG
    org.springframework.amqp.rabbit.core.RabbitAdmin: DEBUG

app:
  oauth2:
    authorized-redirect-uris:
      - http://localhost:3000/oauth2/redirect
      - http://localhost:3001/oauth2/redirect
      - https://latteve.site/oauth2/redirect
      - https://www.latteve.site/oauth2/redirect

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: method
  paths-to-match:
    - /**
