### 프로젝트 생성 요청
POST http://localhost:8080/api/projects
Content-Type: application/json

{
  "projectName": "테스트3",
  "projectImage": "https://image.yes24.com/goods/110126993/XL",
  "recruitmentRoles": [
    {
      "jobId": 1,
      "count": 1
    },
    {
      "jobId": 2,
      "count": 3
    },
    {
      "jobId": 6,
      "count": 4
    }
  ],
  "content": "<h1>피자좋아</h1>",
  "techStack": [
    {
      "techStackId": 3,
      "name": "spring"
    },
    {
      "techStackId": 2,
      "name": "react"
    },
    {
      "techStackId": 1,
      "name": "node"
    }
  ],
  "duration": 4,
  "cycle": 2
}

> {%
client.test("프로젝트 생성에 성공한다.", function() {
    client.assert(response.status === 201, "응답코드가 201아니면 실패");
});
%}



### 프로젝트 요청 목록 조회
@projectId = 1
GET http://localhost:8080/api/projects/{{projectId}}/applications



### 사용자의 프로젝트 상태별로 조회 - 모집중
GET http://localhost:8080/api/projects/my?status=0
Cookie: jwt=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZGFzdHJhMTEyM0BuYXZlci5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwibWVtYmVySWQiOjE5LCJpYXQiOjE3MjU0NTEyNDYsImV4cCI6MTcyNTQ1MzA0Nn0.cy2rp0DWEjaIbIvOOX1EXchbs5o-fArVJdMi-1izd8DXB7F1O_7VOjiI4pE--o1urPbuw5bS2HEHh8rHxrDU_A

### 사용자의 프로젝트 상태별로 조회 - 진행중
GET http://localhost:8080/api/projects/my?status=1
Cookie: jwt=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZGFzdHJhMTEyM0BuYXZlci5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwibWVtYmVySWQiOjE5LCJpYXQiOjE3MjU0NTEyNDYsImV4cCI6MTcyNTQ1MzA0Nn0.cy2rp0DWEjaIbIvOOX1EXchbs5o-fArVJdMi-1izd8DXB7F1O_7VOjiI4pE--o1urPbuw5bS2HEHh8rHxrDU_A
### 사용자의 프로젝트 상태별로 조회 - 종료
GET http://localhost:8080/api/projects/my?status=2
Cookie: jwt=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZGFzdHJhMTEyM0BuYXZlci5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwibWVtYmVySWQiOjE5LCJpYXQiOjE3MjU0NTEyNDYsImV4cCI6MTcyNTQ1MzA0Nn0.cy2rp0DWEjaIbIvOOX1EXchbs5o-fArVJdMi-1izd8DXB7F1O_7VOjiI4pE--o1urPbuw5bS2HEHh8rHxrDU_A
### 사용자가 좋아요 누른 프로젝트 조회
GET http://localhost:8080/api/projects/my/like
Cookie: jwt=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZGFzdHJhMTEyM0BuYXZlci5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwibWVtYmVySWQiOjE5LCJpYXQiOjE3MjU0NTEyNDYsImV4cCI6MTcyNTQ1MzA0Nn0.cy2rp0DWEjaIbIvOOX1EXchbs5o-fArVJdMi-1izd8DXB7F1O_7VOjiI4pE--o1urPbuw5bS2HEHh8rHxrDU_A

### 마이페이지 멤버 정보 조회
GET http://localhost:8080/api/users/me
Cookie: jwt=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZGFzdHJhMTEyM0BuYXZlci5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwibWVtYmVySWQiOjE5LCJpYXQiOjE3MjU0NTEyNDYsImV4cCI6MTcyNTQ1MzA0Nn0.cy2rp0DWEjaIbIvOOX1EXchbs5o-fArVJdMi-1izd8DXB7F1O_7VOjiI4pE--o1urPbuw5bS2HEHh8rHxrDU_A

### 마이페이지에서 멤버 정보 수정
PUT http://localhost:8080/api/users/me
Cookie: jwt=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJsb2VkeTExMjNAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsIm1lbWJlcklkIjo1MCwiaWF0IjoxNzI1OTY1NzA2LCJleHAiOjE3MjU5Njc1MDZ9.9WMH9FHywLXUoMqVoC7c_R6N0IASKSNO1ctRv8nHuCf90TyT3lY2djWZZmQoVHtxZXWEOzOHM3YJlRpTmY31WA
Content-Type: application/json

{
  "imgUrl": "img1",
  "nickname": "반고흐",
  "github": "https://github.com/Jade9846",
  "jobIds": [
    2,5
  ],
  "career": "신입",
  "techStackIds": [
    3
  ],
  "customStacks": [
  ],
  "pr": "string"
}


### 프로젝트 좋아요
POST http://localhost:8080/api/projects/{{projectId}}/like
Cookie: jwt=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ2b3N4amExQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJtZW1iZXJJZCI6MTYsImlhdCI6MTcyNTc1MTE1NywiZXhwIjoxNzI1NzUyOTU3fQ._ZMJm-9zsaxnInBVe4Rk1taH59t9gox3unLdkVLaYbC7sVN68ihMMNITCF7jj-KgLxY4ukf6Z8an3ZEoIZ3J5g
Content-Type: application/json


### 프로젝트 좋아요 취소
DELETE http://localhost:8080/api/projects/{{projectId}}/like
Cookie: jwt=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ2b3N4amExQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJtZW1iZXJJZCI6MTYsImlhdCI6MTcyNTc1MTE1NywiZXhwIjoxNzI1NzUyOTU3fQ._ZMJm-9zsaxnInBVe4Rk1taH59t9gox3unLdkVLaYbC7sVN68ihMMNITCF7jj-KgLxY4ukf6Z8an3ZEoIZ3J5g

### 프로젝트 멤버 승인/거절
@Project_id = 0
@Project_memberId = 0
@Project_isAccepted = 0
PUT http://localhost:8080/api/projects/applications
Cookie: jwt=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ2b3N4amExQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJtZW1iZXJJZCI6MTYsImlhdCI6MTcyNTc1MTE1NywiZXhwIjoxNzI1NzUyOTU3fQ._ZMJm-9zsaxnInBVe4Rk1taH59t9gox3unLdkVLaYbC7sVN68ihMMNITCF7jj-KgLxY4ukf6Z8an3ZEoIZ3J5g
Content-Type: application/json

{
  "projectId": {{Project_id}},
  "memberId": {{Project_memberId}},
  "acceptStatus": {{Project_isAccepted}}
}

### 프로젝트 시작

POST http://localhost:8080/api/projects/start
Cookie: jwt=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ2b3N4amExQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJtZW1iZXJJZCI6MTYsImlhdCI6MTcyNTc1MTE1NywiZXhwIjoxNzI1NzUyOTU3fQ._ZMJm-9zsaxnInBVe4Rk1taH59t9gox3unLdkVLaYbC7sVN68ihMMNITCF7jj-KgLxY4ukf6Z8an3ZEoIZ3J5g
Content-Type: application/json

{
  "projectId": {{Project_id}}
}

### 블루 그린 테스트 3
